### ISSUE TITLE
is_proper_chrom() error with EMA

### ISSUE THREAD

**Issue by pdimens** [pontushojer/NAIBR#3]
Testing this fork of NAIBR on the alignments made for one sample using both BWA and EMA, NAIBR runs without issue on the BWA alignments, but fails on the EMA alignments:

```
2023-05-26 16:39:42,121 - INFO: Found 7 chromosomes with data in BAM
2023-05-26 16:39:42,143 - INFO: running on 4 threads
2023-05-26 16:39:42,145 - INFO: Getting candidates for chromosome 2L
2023-05-26 16:39:42,145 - INFO: Getting candidates for chromosome 2R
2023-05-26 16:39:42,145 - INFO: Getting candidates for chromosome 3L
2023-05-26 16:39:42,145 - INFO: Getting candidates for chromosome 3R
2023-05-26 16:39:42,273 - INFO: Getting candidates for chromosome 4
2023-05-26 16:39:42,340 - INFO: Getting candidates for chromosome X
2023-05-26 16:39:42,353 - INFO: Getting candidates for chromosome Y
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/__main__.py", line 116, in run_naibr
    ) = parse_chromosome(chrom, configs)
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/get_reads.py", line 105, in parse_chromosome
    for read, mate in progress(
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/get_reads.py", line 64, in progress
    for nr, el in enumerate(iterator, start=1):
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/get_reads.py", line 44, in parse_mapped_pairs
    is_proper_chrom(read.next_reference_name)
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/utils.py", line 416, in is_proper_chrom
    return "Un" not in chrom and "random" not in chrom and "hs37d5" not in chrom
TypeError: argument of type 'NoneType' is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pd348/miniconda3/envs/harpy/bin/naibr", line 8, in <module>
    sys.exit(main())
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/__main__.py", line 330, in main
    return run(file_configs)
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/__main__.py", line 252, in run
    chroms_data = parallel_execute(run_with_configs, chromosomes, threads=configs.NUM_THREADS)
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/site-packages/naibr/utils.py", line 563, in parallel_execute
    data = pool.map(function, input_list)
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/pd348/miniconda3/envs/harpy/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by pontushojer** [comment]
Could you post a subset of your BAM for me to try? I have used NAIBR on EMA mapped reads before without issues.

**Comment by pdimens** [comment]
@pontushojer absolutely. Here is a subset of the bam I'm using. I confirmed that the subset triggers the same error. Files hosted here: https://mega.nz/folder/vBJjhahI#W807W1X3DPmSQWcVGFRtxg

**Comment by pontushojer** [comment]
Thanks for sending the subset! I found the issue and added a fix in https://github.com/pontushojer/NAIBR/commit/745044ab95cde4a628a1f0cbaa63408a2a3667cd

This read was causing the error
```
A00470:481:HNYFWDRX2:2:2236:20772:18709	16	2L	443618	60	81M	*	0	0	ACCATTACCACCCACCCTGCCACCGAATGGAGCAGATTACTACCGGATCGAGGATTACCTACCCAGTGGACTGCACACTCC	:FF:FF:FFFFFFF:F:F:FF:FFFFFFFFF:FFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFF::FFFFFFFFFF	NM:i:1	MD:Z:14G66	AS:i:76	XS:i:0	RG:Z:ZS10_221221_15x
```

It seems that your BAM includes singleton reads that are not used in NAIBR. The read is also without barcode so its not form EMA. In the header I saw that you also run BWA on the reads without barcode. Seems some of these might be single end.

**Comment by pdimens** [comment]
Ah yes, the EMA docs suggest mapping the invalid/unbarcoded reads with BWA and merging the two together. I'll test this a little later today, thank you!

**Comment by pdimens** [comment]
The change now works, thank you. Closing this :smile:
